# Generated by Django 5.1.4 on 2025-01-11 08:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('device_number', models.CharField(max_length=50, verbose_name='رقم الجهاز')),
                ('function', models.TextField(verbose_name='وظيفة الجهاز')),
                ('location', models.CharField(max_length=200, verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0, verbose_name='درجة الحرارة')),
                ('manual_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='الوقت اليدوي')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإدخال التلقائي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_readings', to='shared_app.device', verbose_name='الجهاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_user_readings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قراءة',
                'verbose_name_plural': 'القراءات',
                'ordering': ['-entry_time'],
            },
        ),
    ]
