# Generated by Django 3.2.20 on 2025-01-17 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='description',
        ),
        migrations.AddField(
            model_name='device',
            name='device_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='رقم الجهاز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='function',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='وظيفة الجهاز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='موقع الجهاز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الجهاز'),
        ),
        migrations.AlterField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
