# Generated by Django 5.1.4 on 2025-01-25 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20250117_2356'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_readings', to='admin_dashboard.device', verbose_name='الجهاز'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_readings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='القيمة')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإدخال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_readings', to='admin_dashboard.device', verbose_name='الجهاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_readings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قراءة الجهاز',
                'verbose_name_plural': 'قراءات الأجهزة',
                'ordering': ['-entry_time'],
            },
        ),
    ]
