# Generated by Django 5.1.4 on 2025-01-11 08:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0, verbose_name='درجة الحرارة')),
                ('manual_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='الوقت اليدوي')),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإدخال التلقائي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_readings', to='shared_app.device', verbose_name='الجهاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_user_readings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قراءة',
                'verbose_name_plural': 'القراءات',
                'ordering': ['-entry_time'],
            },
        ),
    ]
