# Generated by Django 3.2.20 on 2025-01-19 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_auto_20250117_2356'),
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_readings', to='admin_dashboard.device', verbose_name='الجهاز'),
        ),
    ]
